limabean2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

urlpatterns = [
    path('', include('portal.urls')),
    path('admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portal/urls.py
from django.urls import path

from . import views

app_name = 'portal'
urlpatterns = [
    path('', views.home, name='home'),
    path('researchers/', views.researchers, name='researchers'),
    path('researcher/<int:researcher_id>/', views.researcher_detail, name='researcher_detail'),
    path('posts/', views.posts, name='posts'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
]

portal/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

class Institution(models.Model):
  name = models.CharField(max_length=50)
  short_name = models.CharField(max_length=20)

  def __str__(self):
    return self.short_name

class Researcher(models.Model):
  first_name = models.CharField(max_length=50)
  last_name = models.CharField(max_length=100)
  email = models.EmailField()
  bio = models.TextField(max_length=500)
  lattes_link = models.CharField(max_length=500)
  facebook_link = models.CharField(max_length=500, blank=True, null=True)
  instagram_link = models.CharField(max_length=500, blank=True, null=True)
  twitter_link = models.CharField(max_length=500, blank=True, null=True)
  institution = models.ForeignKey(Institution, models.SET_NULL, blank=True, null=True)
  photo = models.ImageField(upload_to='photos/researchers/')
  is_cover = models.BooleanField()

  def __str__(self):
    return self.first_name

class Article(models.Model):
  title = models.CharField(max_length=100)
  abstract = models.TextField(max_length=600)
  published_at = models.DateField()
  web_link = models.CharField(max_length=500)
  researcher = models.ForeignKey(Researcher, on_delete=models.CASCADE)
  first_author = models.BooleanField()

  def __str__(self):
    return self.title

class Post(models.Model):
  title = models.CharField(max_length=100)
  subtitle = models.CharField(max_length=100)
  abstract = models.TextField(max_length=600)
  content = RichTextUploadingField()
  cover = models.ImageField(upload_to='photos/posts')
  published_at = models.DateField()
  is_cover = models.BooleanField()

  def __str__(self):
    return self.title

class ShortPost(models.Model):
  title = models.CharField(max_length=100)
  abstract = models.TextField(max_length=600)
  photo = models.ImageField(upload_to='photos/short_posts/')
  web_link = models.CharField(max_length=500)
  is_cover = models.BooleanField()

  def __str__(self):
    return self.title

portal/views.py
from django.shortcuts import render, get_object_or_404

from .models import ShortPost, Researcher, Post, Article


def home(request):
    context = {}
    short_posts = ShortPost.objects.filter(is_cover=True)
    researchers = Researcher.objects.filter(is_cover=True)
    posts = Post.objects.filter(is_cover=True)
    context['short_posts'] = short_posts
    context['researchers'] = researchers
    context['posts'] = posts
    return render(request, 'portal/home/_home.html', context)

def researchers(request):
  context = {}
  return render(request, 'portal/researcher/_index.html', context)

def researcher_detail(request, researcher_id):
  context = {}
  researcher = get_object_or_404(Researcher, pk=researcher_id)
  articles = Article.objects.filter(researcher_id=researcher_id)
  context['researcher'] = researcher
  context['articles'] = articles
  return render(request, 'portal/researcher/_detail.html', context)

def posts(request):
  context = {}
  return render(request, 'portal/post/_index.html', context)

def post_detail(request, post_id):
  context = {}
  post = get_object_or_404(Post, pk=post_id)
  context['post'] = post
  return render(request, 'portal/post/_detail.html', context)

portal/templates/portal/__base.html
{% load staticfiles i18n %}
{% load fontawesome %}
<!DOCTYPE html>

<html>

  <head>
    {% block meta_tags %}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% endblock %}
    <title>
      {% block title %}{% trans "LimaBean" %}{% endblock %}
    </title>
    {% block stylesheets %}
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css" />
      <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css" />
      {% fontawesome_stylesheet %}
    {% endblock %}
    {% block javascript %}
      <script src="{% static 'js/jquery-3.3.1.min.js' %}" type="text/javascript"></script>
      <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
    {% endblock %}
    {% block extra_head %}{% endblock %}
  </head>

  <body>
    <header>
      {% include "portal/_navigation.html" %}
    </header>
    <main role="main">
      {% block content %}
      {% endblock %}
      {% include "portal/_footer.html" %}
    </main>
  </body>

</html>

portal/templates/portal/_footer.html
<footer class="container">
  <p class="float-right"><a href="#">Voltar ao topo</a></p>
  <p>&copy; 2019 RGMV, <a href="https://ufpi.br" target="blank">UFPI</a></p>
</footer>

portal/templates/portal/_navigation.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="/">RGMV</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if '/' not in request.path %} active {% endif %}">
        <a class="nav-link" href="/">Início</a>
      </li>
      <li class="nav-item {% if 'posts' in request.path %} active {% endif %}">
        <a class="nav-link" href="{% url 'portal:posts' %}">Publicações</a>
      </li>
      <li class="nav-item {% if 'researchers' in request.path %} active {% endif %}">
        <a class="nav-link" href="{% url 'portal:researchers' %}">Pesquisadores</a>
      </li>
    </ul>
  </div>
</nav>

portal/templates/portal/home/_carousel.html
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    {% for short_post in short_posts %}
      <li data-target="#myCarousel" data-slide-to="{{ forloop.counter }}" class="{% if forloop.first %}active{% endif %}"></li>
    {% endfor %}
  </ol>
  <div class="carousel-inner">
    {% for short_post in short_posts %}
      <div class="carousel-item {% if forloop.first %}active{% endif %}">
        <img src="{{ short_post.photo.url }}" width="100%" height="100%" alt="image">
        <div class="container">
          <div class="carousel-caption text-center">
            <h1>{{ short_post.title }}</h1>
            <p>{{ short_post.abstract }}</p>
            {% if short_post.web_link %}
              <p><a class="btn btn-lg btn-primary" href="{{ short_post.web_link }}" target="blank" role="button">Ler mais</a></p>
            {% endif %}
          </div>
        </div>
      </div>
    {% endfor%}
  </div>
  <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

portal/templates/portal/home/_home.html
{% extends "portal/__base.html" %}

{% block content %}
  {% include "portal/home/_carousel.html" %}
  <div class="container marketing">
    {% include "portal/home/_researchers.html" %}
    {% include "portal/home/_posts.html" %}
  </div>
{% endblock %}

portal/templates/portal/home/_posts.html
{% for post in posts %}
  <hr class="featurette-divider">
  <div class="row featurette">
    <div class="col-md-7">
      <a href="{% url 'portal:post_detail' post.id %}" class="h2">{{ post.title }}.</a>
      <a href="{% url 'portal:post_detail' post.id %}" class="h2"><span class="text-muted"> {{ post.subtitle }}</span></a>
      <a href="{% url 'portal:post_detail' post.id %}" class="h5 lead"><p>{{ post.abstract }}</p></a>
    </div>
    <div class="col-md-5">
      <a href="{% url 'portal:post_detail' post.id %}">
        <img src="{{ post.cover.url }}"  class="featurette-image img-fluid mx-auto" width="500" height="500" alt="cover">
      </a>
    </div>
  </div>
  <hr class="featurette-divider">
{% endfor %}

portal/templates/portal/home/_researchers.html
<!-- Three columns of text below the carousel -->
<div class="row">
  {% for researcher in researchers %}
    <div class="col-lg-4">
      <img src="{{ researcher.photo.url }}" class="rounded-circle" width="140" height="140" alt="photo">
      <h2>{{ researcher.first_name }} {{ researcher.last_name }}</h2>
      <p>{{ researcher.bio }}</p>
      <p><a class="btn btn-secondary" href="{% url 'portal:researcher_detail' researcher.id %}" role="button">Ver detalhes &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
  {% endfor %}
</div><!-- /.row -->

portal/templates/portal/post/_detail.html
{% extends "portal/__base.html" %}

{% load fontawesome %}

{% block content %}
  <div class="container">
    <div class="row mt-5">
      <div class="col">
        <div class="card">
          <div class="card-body">
            <h3>{{ post.title }}</h3>
            <h5>{{ post.subtitle }}</h3>
            <h6>Publicação: {{ post.published_at }}</h6>
          </div>
        </div>
      </div>
    </div>

    <div class="row mt-5">
      <div class="col">
        {{ post.content |safe }}
      </div>
    </div>
  </div>

  <hr class="featurette-divider">
{% endblock %}

portal/templates/portal/post/_index.html
{% extends "portal/__base.html" %}

{% load fontawesome %}

{% block content %}
  <div class="container">
    <div class="row mt-5">
      <div class="col text-center">
        <h2>Listagem de Publicações</h2>
      </div>
    </div>
  </div>

  <hr class="featurette-divider">
{% endblock %}

portal/templates/portal/researcher/_detail.html
{% extends "portal/__base.html" %}

{% load fontawesome %}

{% block content %}
<div class="container">
  <div class="row mt-5">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <img src="{{ researcher.photo.url }}" alt="avatar" width="500" height="500">
        </div>
      </div>
    </div>
    <div class="col">
      <div class="row mb-3">
        <div class="col">
          <div class="card">
            <div class="card-body">
              <div class="row">
                <div class="col">
                  <h2>{{ researcher.first_name }} {{ researcher.last_name }}</h2>
                  <h5>{{ researcher.institution.name }} - {{ researcher.institution.short_name }} </h5>
                </div>
              </div>
              <div class="row mt-3">
                <div class="col">
                  {{ researcher.bio }}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <div class="card">
            <div class="card-body">
              <div class="row">
                <div class="col">
                  <h3>Lattes</h5>
                </div>
              </div>
              <div class="row">
                <div class="col">
                  <ul class="fa-ul">
                    <li> {% fontawesome_icon 'user' li=True %} <a href="{{ researcher.lattes_link }}"
                        target="blank">{{ researcher.lattes_link }}</a></li>
                  </ul>
                </div>
              </div>
              <div class="row">
                <div class="col">
                  <h3>Links Sociais</h5>
                </div>
              </div>
              <div class="row">
                <div class="col">
                  <ul class="fa-ul">
                    {% if researcher.facebook_link %}
                    <li> {% fontawesome_icon 'facebook' li=True %} <a href="{{ researcher.facebook_link }}"
                        target="blank">{{ researcher.facebook_link }}</a></li>
                    {% endif %}
                    {% if researcher.instagram_link %}
                    <li> {% fontawesome_icon 'instagram' li=True %} <a href="{{ researcher.instagram_link }}"
                        target="blank">{{ researcher.instagram_link }}</a></li>
                    {% endif %}
                    {% if researcher.twitter_link %}
                    <li> {% fontawesome_icon 'twitter' li=True %} <a href="{{ researcher.twitter_link }}"
                        target="blank">{{ researcher.twitter_link }}</a></li>
                    {% endif %}
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <hr class="featurette-divider">

  <h2 class="text-center"> Artigos Publicados</h2>
  {% if articles %}
  <div class="row mt-5">
    <div id="accordion">
      {% for article in articles %}
      <div class="card">
        <div class="card-header" id="heading-{{ researcher.id }}-{{ article.id }}">
          <h5 class="mb-0">
            <button class="btn btn-link" data-toggle="collapse"
              data-target="#collapse-{{ researcher.id }}-{{ article.id }}" aria-expanded="expanded"
              aria-controls="collapse-{{ researcher.id }}-{{ article.id }}">
              {{ article.title }}
            </button>
            {% if article.first_author %}
            <span class=" float-right badge badge-secondary">Primeiro Autor</span>
            {% endif %}
          </h5>
        </div>

        <div id="collapse-{{ researcher.id }}-{{ article.id }}" class="collapse {% if forloop.first %}show{% endif %}"
          aria-labelledby="heading-{{ researcher.id }}-{{ article.id }}" data-parent="#accordion">
          <div class="card-body">
            <div class="row">
              <div class="col">
                {{ article.abstract }}
              </div>
            </div>
            {% if article.web_link %}
            <div class="row mt-3">
              <div class="col">
                <a href="{{ article.web_link }}" target="blank" class="float-right btn btn-primary">Ler mais</a>
              </div>
            </div>
            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  {% else %}
  <div class="row mt-5">
    <div class="col text-center">
      <h5>(Sem atrtigos cadastrados para esse pesquisador)</h5>
    </div>
  </div>
  {% endif %}

  <hr class="featurette-divider">

</div>
{% endblock %}

portal/templates/portal/researcher/_index.html
{% extends "portal/__base.html" %}

{% load fontawesome %}

{% block content %}
  <div class="container">
    <div class="row mt-5">
      <div class="col text-center">
        <h2>Listagem de Pesquisadores</h2>
      </div>
    </div>
  </div>

  <hr class="featurette-divider">
{% endblock %}